modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "tough_terrain"
version = "${version}"
displayName = "Tough Terrain"
authors = "moist"
description = '''
A mod which makes digging in the dirt a bit more interesting.
'''
logoFile = "assets/tough_terrain/logo.png"

[[dependencies.tough_terrain]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tough_terrain]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tough_terrain]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tough_terrain.mixins.json"
